server:
  port: 8081

spring:
  application:
    name: "order-service"
  datasource:
    url: jdbc:mysql://localhost:3307/order_service
    username: order_service
    password: order_service
  jpa:
    hibernate:
      ddl-auto: none

inventory:
  uri: http://localhost:8082

springdoc:
  api-docs:
    enabled: true 
    path: /order-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /order-service/swagger-ui.html
    
# Actuator configuration        
management:
  health:
    circuitbreaker:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      
# Resilience4j configuration
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimum-number-of-calls: 5
  timelimiter:
    instances:
      inventory:
        timeout-duration: 3s
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 2s